### PR TITLE
Added CWE-22 fixes, and increased timeouts for test case

### LINKED ISSUE #375: Correct CWE-22 security scanning issue
Code is present in the repository that fails to check for tar file escapes when symbolic links are used.

CodeQL detected.

### PR DESCRIPTION
**Pull request by karlmutch**
fixes #375 

Fixes https://cwe.mitre.org/data/definitions/22.html

Prevent symbolic links from traversing outside of the root directory where a tar file is being unpacked into.

### CODE REVIEW

File: internal/s3/s3.go [hunk 1]
```diff
@@ -394,13 +411,20 @@ func (s *s3Storage) Fetch(ctx context.Context, name string, unpack bool, output
 				return warns, errCtx.Wrap(errGo).With("fileType", fileType).With("stack", stack.Trace().TrimRuntime())
 			}
 
-			path, _ := filepath.Abs(filepath.Join(output, header.Name))
-			if !strings.HasPrefix(path, output) {
-				fmt.Println(errCtx.NewError("archive file name escaped").With("path", path, "output", output, "filename", header.Name).With("stack", stack.Trace().TrimRuntime()).Error())
+			if willEscape(header.Name, output) || willEscape(header.Name, output) {
 				return warns, errCtx.NewError("archive file name escaped").With("filename", header.Name).With("stack", stack.Trace().TrimRuntime())
```
Comment (andreidenissov-cog) [inline internal/s3/s3.go:415]: Why do we do this twice? willEscape() is just a function with no side-effects or not?

File: internal/runner/objectstore.go [hunk 2]
```diff
@@ -479,6 +480,7 @@ func (s *objStore) Fetch(ctx context.Context, name string, unpack bool, output s
 		case s.ErrorC <- err:
 		default:
 		}
+		fmt.Println(spew.Sdump(err), "stack", stack.Trace().TrimRuntime())
 		// If we had a working file get rid of it, this is because leaving it in place will
```
Comment (andreidenissov-cog) [inline internal/runner/objectstore.go:484]: What does spew.Sdump() do? We are adding extra dependency in our code on some (personal?) repo AFAIU.
Is it worth it?

File: internal/s3/s3.go (hunk 1 above)
Comment (karlmutch) [reply internal/s3/s3.go:415]: The function has no side effects.  It is called twice because the symbolic link has two entries implicated, one is the target of the link and the other is the location of the link itself.

File: internal/runner/objectstore.go (hunk 2 above)
Comment (karlmutch) [reply internal/runner/objectstore.go:484]: Yes it has been worth it so far for debugging like output where I want to watch something for a couple of releases while it is deployed.  Go has improved in this area with the format specifier "%+v" but it is still not as useful because it does not have a nice json format which I can used with the observability/wide events side of things.  I am watching the Go releases to see if this comes into the language a bit more.  There have been libraries that over time I have been able to get rid of but it has been slow sometimes to replace utility packages like spew.

File: internal/s3/s3.go (hunk 1 above)
Comment (andreidenissov-cog) [reply internal/s3/s3.go:415]: Yeah, OK. But we have a function with no side effects called twice with identical parameters.

**Review by andreidenissov-cog — APPROVED** [review]

File: internal/s3/s3.go (hunk 1 above)
Comment (karlmutch) [reply internal/s3/s3.go:415]: Ahh yes a bug.  I need the symbolic link target in there.

**Comment by karlmutch** [comment]
Security check deferred to another development branch. Will fix there.

**Comment by karlmutch** [comment]
fixes #375
